---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: data_bags

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[simple-centos7::default]
    attributes:
