name 'simple-centos7'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures simple-centos7'
long_description 'Installs/Configures simple-centos7'
version '0.1.1'
